import { StyleSheet } from "react-native-unistyles"

export const changeIconInlineStyles = StyleSheet.create((theme) => ({
  wrapper: {
    width: "100%",
    alignItems: "center",
    paddingVertical: 20,
    gap: 20,
  },
  iconBox: {
    borderRadius: theme.colors.radius,
    backgroundColor: theme.colors.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  panel: {
    width: "100%",
    paddingHorizontal: 20,
    paddingBottom: 16,
    marginTop: 0,
  },
  listWrapper: {
    borderRadius: theme.colors.radius,
    overflow: "hidden",
    backgroundColor: theme.colors.secondary,
  },
  item: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  itemPressed: {
    opacity: 0.7,
  },
  itemLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  itemTitle: {
    fontWeight: "500",
    fontSize: 18,
    color: theme.colors.onSurface,
  },
  itemChevron: {
    color: theme.colors.onSecondary,
    opacity: 0.6,
  },
  modeScrollContent: {
    flexGrow: 1,
  },
  modeContent: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingBottom: 20,
  },
  modeTitle: {
    marginBottom: 24,
    textAlign: "center",
    color: theme.colors.onSurface,
  },
  emojiTitle: {
    textAlign: "center",
    marginBottom: 32,
    color: theme.colors.onSurface,
  },
  emojiPreviewContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emojiPreviewBox: {
    width: 120,
    height: 120,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.secondary ?? theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    overflow: "hidden",
  },
  emojiPreviewInput: {
    position: "absolute",
    width: "100%",
    height: "100%",
    fontSize: 64,
    fontWeight: "600",
    color: theme.colors.primary,
    textAlign: "center",
    opacity: 0,
  },
  emojiPreviewText: {
    fontSize: 64,
    fontWeight: "600",
    color: theme.colors.primary,
    textAlign: "center",
    lineHeight: 72,
  },
  emojiInstructionContainer: {
    paddingHorizontal: 8,
    marginBottom: 32,
    width: "100%",
    alignItems: "center",
  },
  emojiInstructionText: {
    textAlign: "center",
    color: theme.colors.onSecondary,
    flexShrink: 1,
  },
  modeActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 10,
    marginTop: 16,
    paddingTop: 8,
  },
  pasteOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 12,
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.onSurface,
    opacity: 0.1,
    marginVertical: 16,
  },
  previewContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 24,
  },
  previewBox: {
    width: 160,
    height: 160,
    borderRadius: 16,
    backgroundColor: theme.colors.secondary ?? theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 2,
    borderColor: theme.colors.primary,
  },
  previewPlaceholderIcon: {
    color: theme.colors.primary,
    opacity: 0.6,
  },
  pickOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 12,
  },
  optionIcon: {
    color: theme.colors.primary,
  },
  optionText: {
    color: theme.colors.primary,
    fontSize: 16,
    fontWeight: "500",
  },
}))
