import type { IconSvgName } from "~/components/ui/icon-svg"
import type { TranslationKey } from "~/i18n/config"
import type { Category } from "~/types/categories"

export type CategoryPreset = Omit<
  Category,
  "id" | "colorScheme" | "isArchived" | "name" | "icon"
> & {
  name: TranslationKey // translation key
  icon: IconSvgName
}

/**
 * Preset expense categories for quick setup.
 *
 * @remarks
 * These are default categories that users can use when setting up their account.
 */
export const ExpensePresets: CategoryPreset[] = [
  {
    name: "components.categories.presets.expense.groceries",
    type: "expense",
    icon: "basket",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.transportation",
    type: "expense",
    icon: "car",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.healthcare",
    type: "expense",
    icon: "heart",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.education",
    type: "expense",
    icon: "school",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.shopping",
    type: "expense",
    icon: "shopping-cart",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.dining",
    type: "expense",
    icon: "pizza",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.entertainment",
    type: "expense",
    icon: "headphones",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.housing",
    type: "expense",
    icon: "building",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.fitness",
    type: "expense",
    icon: "activity",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.utilities",
    type: "expense",
    icon: "plug",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.travel",
    type: "expense",
    icon: "plane",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.personalCare",
    type: "expense",
    icon: "sparkles",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.clothing",
    type: "expense",
    icon: "shirt",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.subscriptions",
    type: "expense",
    icon: "refresh",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.insurance",
    type: "expense",
    icon: "shield",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.pets",
    type: "expense",
    icon: "paw-print",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.coffee",
    type: "expense",
    icon: "coffee",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.expense.charity",
    type: "expense",
    icon: "heart-handshake",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

/**
 * Preset income categories for quick setup.
 *
 * @remarks
 * These are default categories that users can use when setting up their account.
 */
export const IncomePresets: CategoryPreset[] = [
  {
    name: "components.categories.presets.income.salary",
    type: "income",
    icon: "wallet",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.income.freelance",
    type: "income",
    icon: "briefcase",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.income.investment",
    type: "income",
    icon: "trending-up",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.income.business",
    type: "income",
    icon: "building-bank",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.income.gift",
    type: "income",
    icon: "gift",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.income.rental",
    type: "income",
    icon: "home-share",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.income.dividends",
    type: "income",
    icon: "coin-pound",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.income.bonus",
    type: "income",
    icon: "star",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.income.sideIncome",
    type: "income",
    icon: "affiliate",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.income.pension",
    type: "income",
    icon: "clock",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.income.taxRefund",
    type: "income",
    icon: "receipt",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.income.cashback",
    type: "income",
    icon: "coins",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.income.commission",
    type: "income",
    icon: "percentage",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "components.categories.presets.income.allowance",
    type: "income",
    icon: "cash-banknote",
    colorSchemeName: "",
    transactionCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
